### ISSUE TITLE
Question: rwreg init() does not load vfat3 routines, is this a bug?

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/reg_utils#20]
## Brief summary of issue

So trying to debug problems experienced:

http://cmsonline.cern.ch/cms-elog/1050906
http://cmsonline.cern.ch/cms-elog/1050905

Basically modules defined in `rwreg.so` and in:

```
from reg_utils.reg_interface.common.reg_base_ops
```

Function without problem, but those in xhal (lubrpcman.so) do not.  And I'm wondering what the reason is.

Also I see the load here is version 1.0.1.  Did we change this from 1.0.0 recently or was it always 1.0.0?  Perhaps one of the issues I'm facing is that there is some compilation issue in which only a subset of the libaries on the DAQ machines (or on the cards themselves) are using 1.0.0?  

I will try to recompile the libraries and place them on the cards...

Perhaps a separate issue on the xhal repo should be opened, but I am not yet sure what the problem is.

### Types of issue

- [ ] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)
- [X] Question 

## Current Behavior

https://github.com/cms-gem-daq-project/reg_utils/blob/aa7e284221dd859f9a80bd036784c78edb788fcd/rwreg/x86_64/src/rwreg.cc#L50-L56

## Your Environment

* Version used: Unknown, what's the package name to use with `yum info`?

**Comment by mexanick** [comment]
I do believe we are on v1.0.1 for a long time already

**Comment by bdorney** [comment]
But shouldn't the above also have a line like:

```
 		ASSERT(rpc.load_module("vfat3", "vfat3 v1.0.1")); 
```

Otherwise what is loading the configure routines?

**Comment by mexanick** [comment]
It should be done in rpcman library, not in tthis one. This one will be even more cleaned in future

**Comment by bdorney** [comment]
Understood, closing issue.
