### ISSUE TITLE
[question] Return types of read functions

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/reg_utils#40]
## Brief summary of issue
In reviewing other PRs, I've noticed a lot of gymnastics being done with the return types of the various `read` functions.
@bdorney pointed me to
https://github.com/cms-gem-daq-project/reg_utils/blob/4d87a368168ec6951aaa8f9e5d9b9e36125a7aeb/python/reg_interface/common/reg_base_ops.py#L25-L27

Why are these returned as `str` types?

**Comment by mexanick** [comment]
I think it was done like this for CLI output. We can consider a change here, however the primary goal of this module is to serve the CLI.

**Comment by jsturdy** [comment]
OK, I see, I think the "primary" goal has shifted (lots of tools are now using this it seems), so it *might* be worth it to think about changing, but we can table that until after we have migrated the rest of the SW and have a more complete picture of the long term architecture.

**Comment by lpetre-ulb** [comment]
While this is a very valid question, these tools will remain legacy only and won't be ported to the development branch. Thus, the return types will likely never be fixed.
