### ISSUE TITLE
Question: getOHlist appears in twice, can we remove one?

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/reg_utils#44]
## Brief summary of issue

The function `getOHlist` appears twice in two different files:

https://github.com/cms-gem-daq-project/reg_utils/blob/7b9cf050c63dae5f3a9b5803389130cff2f039fa/python/reg_interface/common/sca_utils.py#L119-L124

https://github.com/cms-gem-daq-project/reg_utils/blob/7b9cf050c63dae5f3a9b5803389130cff2f039fa/python/reg_interface/common/sca_common_utils.py#L6-L11

I can't see why this would be the case.

If there's no objection we should remove one of them.  Which one...?

### Types of issue

- [x] Bad Design...?
- [ ] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

Function should only appear in one location.

## Current Behavior

Function appears in two locations.

## Your Environment

* Version used: 7b9cf050c63dae5f3a9b5803389130cff2f039fa
* Shell used:

**Comment by mexanick** [comment]
I believe this is a post-refactoring remnants. Should be removed from `sca_utils.py` and sourced from `sca_common_utils.py`. Would you mind fixing it and test quickly?

**Comment by bdorney** [comment]
Addressed by #46
